### ISSUE TITLE
what is this error - io.UnsupportedOperation: fileno

### ISSUE THREAD

**Issue by za-wa-n-go** [gokayfem/ComfyUI_VLM_nodes#10]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "X:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\PIL\ImageFile.py", line 515, in _save
io.UnsupportedOperation: fileno

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "X:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_VLM_nodes\nodes\llavaloader.py", line 88, in generate_text
    pil_image.save(buffer, format="JPEG")  # You can change the format if needed
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\PIL\Image.py", line 2432, in save
    # Open also for reading ("+"), because TIFF save_all
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\PIL\JpegImagePlugin.py", line 824, in _save
    ImageFile._save(im, fp, [("jpeg", (0, 0) + im.size, 0, rawmode)], bufsize)
  File "X:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\PIL\ImageFile.py", line 519, in _save
  File "X:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\PIL\ImageFile.py", line 528, in _encode_tile
    im.encoderconfig = ()
              ^^^^^^^^^^^^
  File "X:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\PIL\Image.py", line 437, in _getencoder
    return _E(self.scale + other.scale, self.offset + other.offset)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: function takes at most 14 arguments (17 given)

**Comment by WesleyKapow** [comment]
I'm hitting this as well. What was the fix here?

**Comment by gokayfem** [comment]
try png or jpeg files
