### ISSUE TITLE
After updating comfyui's pip to the latest, I ComfyUI_VLM_nodes the following error message: FileNotFoundError: [WinError 3] εͳҲָ·: 'D:psûw11variableCUDA11.8bin'  Cannot import E:ComfyUI_FK_202406ComfyUIcustom_nodesComfyUI_VLM_nodes module for custom nodes: [WinError 3] ϵͳҲָ·: 'D:psûw11variableCUDA11.8bin'

### ISSUE THREAD

**Issue by tang690179** [gokayfem/ComfyUI_VLM_nodes#104]
After updating comfyui's pip to the latest, I ComfyUI_VLM_nodes the following error message: FileNotFoundError: [WinError 3] εͳҲָ·: 'D:psûw11variableCUDA11.8bin'

Traceback (most recent call last):
  File "E:\ComfyUI_FK_202406\ComfyUI\nodes.py", line 1941, in load_custom_node
    module_spec.loader.exec_module(module)
  File "", line 940, in exec_module
  File "", line 241, in _call_with_frames_removed
  File "E:\ComfyUI_FK_202406\ComfyUI\custom_nodes\ComfyUI_VLM_nodes\__init__.py", line 70, in 
    imported_module = importlib.import_module(f".nodes.{module_name}", __name__)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_FK_202406\python_embeded\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "", line 1204, in _gcd_import
  File "", line 1176, in _find_and_load
  File "", line 1147, in _find_and_load_unlocked
  File "", line 690, in _load_unlocked
  File "", line 940, in exec_module
  File "", line 241, in _call_with_frames_removed
  File "E:\ComfyUI_FK_202406\ComfyUI\custom_nodes\ComfyUI_VLM_nodes\nodes\llavaloader.py", line 4, in 
    from llama_cpp import Llama
  File "E:\ComfyUI_FK_202406\python_embeded\Lib\site-packages\llama_cpp\__init__.py", line 1, in 
    from .llama_cpp import *
  File "E:\ComfyUI_FK_202406\python_embeded\Lib\site-packages\llama_cpp\llama_cpp.py", line 83, in 
    _lib = _load_shared_library(_lib_base_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_FK_202406\python_embeded\Lib\site-packages\llama_cpp\llama_cpp.py", line 59, in _load_shared_library
    os.add_dll_directory(os.path.join(os.environ["CUDA_PATH"], "bin"))
  File "", line 1119, in add_dll_directory
FileNotFoundError: [WinError 3] ϵͳҲָ·: 'D:\\ps\\û\\w11\\variable\\CUDA11.8\\bin'

Cannot import E:\ComfyUI_FK_202406\ComfyUI\custom_nodes\ComfyUI_VLM_nodes module for custom nodes: [WinError 3] ϵͳҲָ·: 'D:\\ps\\û\\w11\\variable\\CUDA11.8\\bin'

**Comment by sharpcj** [comment]
I got the same error.

**Comment by dzy1128** [comment]
Have you solved the problem?

**Comment by gokayfem** [comment]
Should be fixed. Importing the pack no longer touches CUDA paths or environment variables — importing performs no network access, no compilation, no package install, and no VRAM allocation. That is enforced by a test asserting the source contains no `pip install` and no `subprocess.run`.

The malformed `CUDA11.8/bin` path in your log was being read at import time; nothing does that now.

If this still happens on **3.3.1**, please reopen with the new bug report template — it asks for the `VLM Runtime Diagnostics` node output, which captures the environment detail these older reports were missing.
