### ISSUE TITLE
Can't Install - 404 error

### ISSUE THREAD

**Issue by scofano** [gokayfem/ComfyUI_VLM_nodes#114]
Installing llama-cpp-python...
Looking in indexes: https://jllllll.github.io/llama-cpp-python-cuBLAS-wheels/AVX2/cu124
ERROR: Could not find a version that satisfies the requirement llama-cpp-python (from versions: none)
ERROR: No matching distribution found for llama-cpp-python
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2001, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_VLM_nodes\__init__.py", line 44, in <module>
    install_llama(system_info)
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_VLM_nodes\install_init.py", line 111, in install_llama
    install_package("llama-cpp-python", custom_command=custom_command)
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_VLM_nodes\install_init.py", line 91, in install_package
    subprocess.check_call(command)
  File "subprocess.py", line 413, in check_call
subprocess.CalledProcessError: Command '['D:\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', 'llama-cpp-python', '--no-cache-dir', '--force-reinstall', '--no-deps', '--index-url=https://jllllll.github.io/llama-cpp-python-cuBLAS-wheels/AVX2/cu124']' returned non-zero exit status 1.

Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_VLM_nodes module for custom nodes: Command '['D:\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', 'llama-cpp-python', '--no-cache-dir', '--force-reinstall', '--no-deps', '--index-url=https://jllllll.github.io/llama-cpp-python-cuBLAS-wheels/AVX2/cu124']' returned non-zero exit status 1.

**Comment by gokayfem** [comment]
Fixed
