### ISSUE TITLE
Exception during processing !!! 'BitsAndBytesConfig' object has no attribute 'get_loading_attributes'

### ISSUE THREAD

**Issue by Erwin11** [gokayfem/ComfyUI_VLM_nodes#126]
![BitsAndBytesConfig - 2024-11-04 12 58 46](https://github.com/user-attachments/assets/2a5c05c7-0cf8-4b2e-a833-3674705b86f7)

transformers  is 4.47.0.dev0

```
FETCH DATA from: E:\AI\ComfyUI\ComfyUI-webui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[]
[]
got prompt
{'type': 'image', 'image': 'E:\\AI\\ComfyUI\\ComfyUI-webui\\ComfyUI_windows_portable\\ComfyUI\\input\\00392Vvvgy1hl1qtryjw7j60w016ogxb02 (2).jpg'}
[{'type': 'image', 'image': 'E:\\AI\\ComfyUI\\ComfyUI-webui\\ComfyUI_windows_portable\\ComfyUI\\input\\00392Vvvgy1hl1qtryjw7j60w016ogxb02 (2).jpg'}]
!!! Exception during processing !!! 'BitsAndBytesConfig' object has no attribute 'get_loading_attributes'
Traceback (most recent call last):
  File "E:\AI\ComfyUI\ComfyUI-webui\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI\ComfyUI-webui\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI\ComfyUI-webui\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\AI\ComfyUI\ComfyUI-webui\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI\ComfyUI-webui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Qwen2-VL-Instruct\nodes.py", line 131, in inference
    self.model = Qwen2VLForConditionalGeneration.from_pretrained(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI\ComfyUI-webui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\modeling_utils.py", line 3647, in from_pretrained
    config.quantization_config = AutoHfQuantizer.merge_quantization_configs(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI\ComfyUI-webui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\quantizers\auto.py", line 180, in merge_quantization_configs
    loading_attr_dict = quantization_config_from_args.get_loading_attributes()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BitsAndBytesConfig' object has no attribute 'get_loading_attributes'

Prompt executed in 327.25 seconds

```
Help! how to fix it?

**Comment by EnragedAntelope** [comment]
I am going to submit a suggested fix for this, thanks for letting us know.

**Comment by EnragedAntelope** [comment]
Update and retry please.

**Comment by Erwin11** [comment]
@EnragedAntelope 
Thanks for hotfix it, But it still doesn't work.

GPTQ-Int8 ：
![Qwen2-int8-not works](https://github.com/user-attachments/assets/a5f3b9fe-9d8c-426d-9fc8-75d973c36955)

Fortunately, Qwen2-VL-2B model is working.
![Qwen2 2B-works fine](https://github.com/user-attachments/assets/8f33a96a-3d76-4f5a-bf9c-f448ba95e3c3)

I'm using it now. Good Day.

**Comment by EnragedAntelope** [comment]
Hi, sorry I missed this earlier. I looked into the issue and supposedly it is just due to older version of transformers. Can you try from your command line in your activated comfyui python environment (as needed):
pip install -U transformers bitsandbytes

then restart comfy and retry?

**Comment by Erwin11** [comment]
transformers version is  4.47.0.dev0
I'm close it. Qwen2-VL-2B works for me
