### ISSUE TITLE
Is this not possible to run on GoogleColab comfyui?

### ISSUE THREAD

**Issue by AMINEMM13** [gokayfem/ComfyUI_VLM_nodes#22]
No matter how many times I install it, it doesn't run.

TypeError: Failed to fetch

   Custom Nodes for Vision Language Models (VLM) , Large Language Models (LLM), Image Captioning, Automatic Prompt Generation, Creative and Consistent Prompt Suggestion, Keyword Extraction

#read_workflow_json_files_all /content/drive/MyDrive/install_comfyui/custom_nodes/comfyui-mixlab-nodes/app/
data_path:  /content/drive/MyDrive/install_comfyui/custom_nodes/comfyui-mixlab-nodes/data
got prompt
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
  File "/content/drive/MyDrive/install_comfyui/server.py", line 47, in cache_control
    response: web.Response = await handler(request)
  File "/content/drive/MyDrive/install_comfyui/server.py", line 474, in post_prompt
    valid = execution.validate_prompt(prompt)
  File "/content/drive/MyDrive/install_comfyui/execution.py", line 620, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
KeyError: 'class_type'

**Comment by gokayfem** [comment]
https://colab.research.google.com/drive/1kNxINwZOCVyYiirUjFezaFhQ_nPZztS3?usp=sharing

VLM nodes it works perfectly in this colab notebook. I think its the mixlab-nodes gives you error not VLM nodes.

**Comment by AMINEMM13** [comment]
Thanks. I trid your colab file. but problem is same.  problem seems to occur in Load everything path, and the error message is the same. I also changed the path to the yaml file.

**Comment by gokayfem** [comment]
its working now in colab.
