### ISSUE TITLE
Fails to load under a Linux ROCm environment

### ISSUE THREAD

**Issue by ricperry** [gokayfem/ComfyUI_VLM_nodes#26]
```
All packages from requirements.txt are installed and up to date.
Traceback (most recent call last):
  File "/sab_files/AI_Projects/ComfyUI/nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/sab_files/AI_Projects/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/__init__.py", line 29, in <module>
    system_info = get_system_info()
  File "/sab_files/AI_Projects/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/install_init.py", line 48, in get_system_info
    system_info['cuda_version'] = "cu" + torch.version.cuda.replace(".", "").strip()
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by gokayfem** [comment]
AMD cards not supported for now

**Comment by ricperry** [comment]
The mac branch works. Thanks for the updates!
