### ISSUE TITLE
Cannot Import ComfyUI_VLM_nodes

### ISSUE THREAD

**Issue by camoody1** [gokayfem/ComfyUI_VLM_nodes#40]
Error during ComfyUI startup...

```
Traceback (most recent call last):
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_VLM_nodes\__init__.py", line 43, in <module>
    system_info = get_system_info()
                  ^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_VLM_nodes\install_init.py", line 52, in get_system_info
    system_info['avx2'] = 'avx2' in cpuinfo.get_cpu_info()['flags']
                                    ^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cpuinfo\cpuinfo.py", line 2762, in get_cpu_info
  File "json\__init__.py", line 359, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Cannot import H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_VLM_nodes module for custom nodes: Expecting value: line 1 column 1 (char 0)
```

Any suggestions?

**Comment by camoody1** [comment]
@gokayfem That did it! Thank you for the prompt reply and fix!

Have a great Friday!
