### ISSUE TITLE
vlm nodes wont import AttributeError: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by GoDJr** [gokayfem/ComfyUI_VLM_nodes#5]
Do the VLM nodes need a CUDA device? im on ROCM and im seeing this error:

[11:34 PM]
Traceback (most recent call last):
  File "/home/sagar/ComfyUI/nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in callwith_frames_removed
  File "/home/sagar/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/__init.py", line 29, in <module>
    system_info = get_system_info()
  File "/home/sagar/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/install_init.py", line 48, in get_system_info
    system_info['cuda_version'] = "cu" + torch.version.cuda.replace(".", "").strip()
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by gokayfem** [comment]
yes only works for nvidia gpus for now
