### ISSUE TITLE
Not working for me... :(

### ISSUE THREAD

**Issue by davedaverave** [gokayfem/ComfyUI_VLM_nodes#54]
llama-cpp installed
Traceback (most recent call last):
  File "/notebooks/ComfyUI/nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/__init__.py", line 46, in <module>
    imported_module = importlib.import_module(f".nodes.{module_name}", __name__)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/nodes/moondream_script.py", line 1, in <module>
    from .moondream import VisionEncoder, TextModel
  File "/notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/nodes/moondream/__init__.py", line 1, in <module>
    from .vision_encoder import VisionEncoder
  File "/notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/nodes/moondream/vision_encoder.py", line 4, in <module>
    from torchvision.transforms.v2 import (
  File "/usr/local/lib/python3.9/dist-packages/torchvision/transforms/v2/__init__.py", line 3, in <module>
    from . import functional  # usort: skip
  File "/usr/local/lib/python3.9/dist-packages/torchvision/transforms/v2/functional/__init__.py", line 3, in <module>
    from ._utils import is_pure_tensor, register_kernel  # usort: skip
  File "/usr/local/lib/python3.9/dist-packages/torchvision/transforms/v2/functional/_utils.py", line 5, in <module>
    from torchvision import tv_tensors
  File "/usr/local/lib/python3.9/dist-packages/torchvision/tv_tensors/__init__.py", line 3, in <module>
    from ._bounding_boxes import BoundingBoxes, BoundingBoxFormat
  File "/usr/local/lib/python3.9/dist-packages/torchvision/tv_tensors/_bounding_boxes.py", line 9, in <module>
    from ._tv_tensor import TVTensor
  File "/usr/local/lib/python3.9/dist-packages/torchvision/tv_tensors/_tv_tensor.py", line 6, in <module>
    from torch._C import DisableTorchFunctionSubclass
ImportError: cannot import name 'DisableTorchFunctionSubclass' from 'torch._C' (/usr/local/lib/python3.9/dist-packages/torch/_C.cpython-39-x86_64-linux-gnu.so)

Cannot import /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes module for custom nodes: cannot import name 'DisableTorchFunctionSubclass' from 'torch._C' (/usr/local/lib/python3.9/dist-packages/torch/_C.cpython-39-x86_64-linux-gnu.so)

**Comment by gokayfem** [comment]
you need to update your python somehow dave. most of my nodes needs python above 3.9.

**Comment by davedaverave** [comment]
i'm crying in 50$ paperspace subscription .....
