### ISSUE TITLE
DEFAULT_ETAG_TIMEOUT

### ISSUE THREAD

**Issue by davedaverave** [gokayfem/ComfyUI_VLM_nodes#6]
cannot import name 'DEFAULT_ETAG_TIMEOUT' from 'huggingface_hub.constants' (/usr/local/lib/python3.9/dist-packages/huggingface_hub/constants.py)

**Comment by davedaverave** [comment]
And now i get this Traceback (most recent call last):
  File "/notebooks/ComfyUI/nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/__init__.py", line 45, in <module>
    imported_module = importlib.import_module(f".nodes.{module_name}", __name__)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/nodes/moondream_script.py", line 1, in <module>
    from .moondream import VisionEncoder, TextModel
  File "/notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/nodes/moondream/__init__.py", line 1, in <module>
    from .vision_encoder import VisionEncoder
  File "/notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/nodes/moondream/vision_encoder.py", line 4, in <module>
    from torchvision.transforms.v2 import (
  File "/usr/local/lib/python3.9/dist-packages/torchvision/transforms/v2/__init__.py", line 3, in <module>
    from . import functional  # usort: skip
  File "/usr/local/lib/python3.9/dist-packages/torchvision/transforms/v2/functional/__init__.py", line 3, in <module>
    from ._utils import is_pure_tensor, register_kernel  # usort: skip
  File "/usr/local/lib/python3.9/dist-packages/torchvision/transforms/v2/functional/_utils.py", line 5, in <module>
    from torchvision import tv_tensors
  File "/usr/local/lib/python3.9/dist-packages/torchvision/tv_tensors/__init__.py", line 3, in <module>
    from ._bounding_boxes import BoundingBoxes, BoundingBoxFormat
  File "/usr/local/lib/python3.9/dist-packages/torchvision/tv_tensors/_bounding_boxes.py", line 9, in <module>
    from ._tv_tensor import TVTensor
  File "/usr/local/lib/python3.9/dist-packages/torchvision/tv_tensors/_tv_tensor.py", line 6, in <module>
    from torch._C import DisableTorchFunctionSubclass
ImportError: cannot import name 'DisableTorchFunctionSubclass' from 'torch._C' (/usr/local/lib/python3.9/dist-packages/torch/_C.cpython-39-x86_64-linux-gnu.so)

Cannot import /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes module for custom nodes: cannot import name 'DisableTorchFunctionSubclass' from 'torch._C' (/usr/local/lib/python3.9/dist-packages/torch/_C.cpython-39-x86_64-linux-gnu.so)

**Comment by gokayfem** [comment]
![image](https://github.com/gokayfem/ComfyUI_VLM_nodes/assets/88277926/2cbcbc48-dd6d-4250-ae17-a5890124f622)

can you update your python dependencies and try again

**Comment by davedaverave** [comment]
I'm on jupyter lab, is there a code i should type to update py depndencies?

**Comment by gokayfem** [comment]
cd update
..\python_embeded\python.exe .\update.py
..\python_embeded\python.exe -s -m pip install -r ../ComfyUI/requirements.txt

**Comment by davedaverave** [comment]
i tryed starting comfyUI and it says that: ```
** ComfyUI startup time: 2024-02-07 20:58:03.335040
** Platform: Linux
** Python version: 3.9.16 (main, Dec  7 2022, 01:11:51) 
[GCC 9.4.0]
** Python executable: /usr/local/bin/python
** Log path: /notebooks/comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: /notebooks/ComfyUI/custom_nodes/rgthree-comfy
   0.0 seconds: /notebooks/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 48677 MB, total RAM 45140 MB
xformers version: 0.0.24
Set vram state to: HIGH_VRAM
Device: cuda:0 NVIDIA RTX A6000 : native
VAE dtype: torch.bfloat16
Using xformers cross attention
Traceback (most recent call last):
  File "/notebooks/ComfyUI/main.py", line 76, in <module>
    import execution
  File "/notebooks/ComfyUI/execution.py", line 11, in <module>
    import nodes
  File "/notebooks/ComfyUI/nodes.py", line 20, in <module>
    import comfy.diffusers_load
  File "/notebooks/ComfyUI/comfy/diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "/notebooks/ComfyUI/comfy/sd.py", line 13, in <module>
    from . import model_detection
  File "/notebooks/ComfyUI/comfy/model_detection.py", line 1, in <module>
    import comfy.supported_models
  File "/notebooks/ComfyUI/comfy/supported_models.py", line 5, in <module>
    from . import sd1_clip
  File "/notebooks/ComfyUI/comfy/sd1_clip.py", line 3, in <module>
    from transformers import CLIPTokenizer
  File "/usr/local/lib/python3.9/dist-packages/transformers/__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "/usr/local/lib/python3.9/dist-packages/transformers/dependency_versions_check.py", line 57, in <module>
    require_version_core(deps[pkg])
  File "/usr/local/lib/python3.9/dist-packages/transformers/utils/versions.py", line 117, in require_version_core
    return require_version(requirement, hint)
  File "/usr/local/lib/python3.9/dist-packages/transformers/utils/versions.py", line 111, in require_version
    _compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
  File "/usr/local/lib/python3.9/dist-packages/transformers/utils/versions.py", line 44, in _compare_versions
    raise ImportError(
ImportError: huggingface-hub>=0.19.3,<1.0 is required for a normal functioning of this module, but found huggingface-hub==0.10.0.
Try: `pip install transformers -U` or `pip install -e '.[dev]'` if you're working with git main
```

**Comment by davedaverave** [comment]
i Tryed uninstalling the requirment package and install them freshlky with !pip install -r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt

and it give me this error: Collecting openai>=0.27.8
  Downloading openai-1.11.1-py3-none-any.whl (226 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 226.1/226.1 kB 27.5 MB/s eta 0:00:00
Collecting accelerate>=0.25.0
  Downloading accelerate-0.26.1-py3-none-any.whl (270 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 270.9/270.9 kB 73.4 MB/s eta 0:00:00
Collecting huggingface-hub==0.20.1
  Downloading huggingface_hub-0.20.1-py3-none-any.whl (330 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 330.1/330.1 kB 71.3 MB/s eta 0:00:00
Collecting Pillow>=10.1.0
  Downloading pillow-10.2.0-cp39-cp39-manylinux_2_28_x86_64.whl (4.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 111.3 MB/s eta 0:00:0000:01
Collecting transformers>=4.36.2
  Downloading transformers-4.37.2-py3-none-any.whl (8.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 129.7 MB/s eta 0:00:0000:01
Collecting torch<3.0.0,>=2.0.1
  Downloading torch-2.2.0-cp39-cp39-manylinux1_x86_64.whl (755.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 755.5/755.5 MB 3.6 MB/s eta 0:00:0000:0100:01
Collecting torchvision>=0.15.2
  Downloading torchvision-0.17.0-cp39-cp39-manylinux1_x86_64.whl (6.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 113.4 MB/s eta 0:00:00a 0:00:01
Collecting einops>=0.7.0
  Downloading einops-0.7.0-py3-none-any.whl (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.6/44.6 kB 17.8 MB/s eta 0:00:00
Collecting safetensors>=0.4.1
  Downloading safetensors-0.4.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 26.3 MB/s eta 0:00:00ta 0:00:01
Collecting py-cpuinfo
  Downloading py_cpuinfo-9.0.0-py3-none-any.whl (22 kB)
Collecting gitpython
  Downloading GitPython-3.1.41-py3-none-any.whl (196 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.4/196.4 kB 58.2 MB/s eta 0:00:00
Collecting moviepy
  Downloading moviepy-1.0.3.tar.gz (388 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 388.3/388.3 kB 78.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting opencv-python
  Downloading opencv_python-4.9.0.80-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (62.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.2/62.2 MB 33.9 MB/s eta 0:00:0000:0100:01
Collecting scikit-build
  Downloading scikit_build-0.17.6-py3-none-any.whl (84 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.3/84.3 kB 28.4 MB/s eta 0:00:00
Collecting typing
  Downloading typing-3.7.4.3.tar.gz (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.6/78.6 kB 23.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting diskcache
  Downloading diskcache-5.6.3-py3-none-any.whl (45 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 13.7 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.9/dist-packages (from huggingface-hub==0.20.1->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 3)) (3.9.0)
Requirement already satisfied: requests in /usr/local/lib/python3.9/dist-packages (from huggingface-hub==0.20.1->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 3)) (2.28.2)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.9/dist-packages (from huggingface-hub==0.20.1->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 3)) (4.64.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.9/dist-packages (from huggingface-hub==0.20.1->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 3)) (4.9.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.9/dist-packages (from huggingface-hub==0.20.1->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 3)) (2024.2.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.9/dist-packages (from huggingface-hub==0.20.1->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 3)) (5.4.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.9/dist-packages (from huggingface-hub==0.20.1->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 3)) (23.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.9/dist-packages (from openai>=0.27.8->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 1)) (1.9.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.9/dist-packages (from openai>=0.27.8->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.9/dist-packages (from openai>=0.27.8->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 1)) (0.23.1)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.9/dist-packages (from openai>=0.27.8->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 1)) (3.6.2)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.9/dist-packages (from openai>=0.27.8->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 1)) (1.9.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.9/dist-packages (from accelerate>=0.25.0->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 2)) (1.23.5)
Requirement already satisfied: psutil in /usr/local/lib/python3.9/dist-packages (from accelerate>=0.25.0->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 2)) (5.9.4)
Requirement already satisfied: tokenizers<0.19,>=0.14 in /usr/local/lib/python3.9/dist-packages (from transformers>=4.36.2->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 5)) (0.15.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.9/dist-packages (from transformers>=4.36.2->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 5)) (2022.10.31)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.9/dist-packages (from torch<3.0.0,>=2.0.1->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 6)) (3.1.2)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /usr/local/lib/python3.9/dist-packages (from torch<3.0.0,>=2.0.1->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 6)) (12.1.3.1)
Requirement already satisfied: nvidia-nccl-cu12==2.19.3 in /usr/local/lib/python3.9/dist-packages (from torch<3.0.0,>=2.0.1->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 6)) (2.19.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /usr/local/lib/python3.9/dist-packages (from torch<3.0.0,>=2.0.1->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 6)) (12.1.105)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /usr/local/lib/python3.9/dist-packages (from torch<3.0.0,>=2.0.1->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 6)) (11.0.2.54)
Requirement already satisfied: networkx in /usr/local/lib/python3.9/dist-packages (from torch<3.0.0,>=2.0.1->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 6)) (3.0)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /usr/local/lib/python3.9/dist-packages (from torch<3.0.0,>=2.0.1->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 6)) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /usr/local/lib/python3.9/dist-packages (from torch<3.0.0,>=2.0.1->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 6)) (11.4.5.107)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /usr/local/lib/python3.9/dist-packages (from torch<3.0.0,>=2.0.1->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 6)) (12.1.105)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /usr/local/lib/python3.9/dist-packages (from torch<3.0.0,>=2.0.1->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 6)) (12.1.0.106)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /usr/local/lib/python3.9/dist-packages (from torch<3.0.0,>=2.0.1->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 6)) (12.1.105)
Requirement already satisfied: triton==2.2.0 in /usr/local/lib/python3.9/dist-packages (from torch<3.0.0,>=2.0.1->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 6)) (2.2.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /usr/local/lib/python3.9/dist-packages (from torch<3.0.0,>=2.0.1->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 6)) (12.1.105)
Requirement already satisfied: sympy in /usr/local/lib/python3.9/dist-packages (from torch<3.0.0,>=2.0.1->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 6)) (1.11.1)
Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /usr/local/lib/python3.9/dist-packages (from torch<3.0.0,>=2.0.1->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 6)) (8.9.2.26)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.9/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch<3.0.0,>=2.0.1->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 6)) (12.3.101)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.9/dist-packages (from gitpython->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 12)) (4.0.10)
Requirement already satisfied: decorator<5.0,>=4.0.2 in /usr/local/lib/python3.9/dist-packages (from moviepy->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 13)) (4.4.2)
Requirement already satisfied: proglog<=1.0.0 in /usr/local/lib/python3.9/dist-packages (from moviepy->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 13)) (0.1.10)
Requirement already satisfied: imageio<3.0,>=2.5 in /usr/local/lib/python3.9/dist-packages (from moviepy->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 13)) (2.25.0)
Requirement already satisfied: imageio_ffmpeg>=0.2.0 in /usr/local/lib/python3.9/dist-packages (from moviepy->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 13)) (0.4.8)
Requirement already satisfied: setuptools>=42.0.0 in /usr/local/lib/python3.9/dist-packages (from scikit-build->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 15)) (66.1.1)
Requirement already satisfied: wheel>=0.32.0 in /usr/local/lib/python3.9/dist-packages (from scikit-build->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 15)) (0.35.1)
Requirement already satisfied: tomli in /usr/local/lib/python3.9/dist-packages (from scikit-build->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 15)) (2.0.1)
Requirement already satisfied: idna>=2.8 in /usr/lib/python3/dist-packages (from anyio<5,>=3.5.0->openai>=0.27.8->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 1)) (2.8)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.9/dist-packages (from gitdb<5,>=4.0.1->gitpython->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 12)) (5.0.0)
Requirement already satisfied: httpcore<0.17.0,>=0.15.0 in /usr/local/lib/python3.9/dist-packages (from httpx<1,>=0.23.0->openai>=0.27.8->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 1)) (0.15.0)
Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from httpx<1,>=0.23.0->openai>=0.27.8->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 1)) (2019.11.28)
Requirement already satisfied: rfc3986[idna2008]<2,>=1.3 in /usr/local/lib/python3.9/dist-packages (from httpx<1,>=0.23.0->openai>=0.27.8->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 1)) (1.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.9/dist-packages (from requests->huggingface-hub==0.20.1->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 3)) (2.1.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests->huggingface-hub==0.20.1->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 3)) (1.26.14)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.9/dist-packages (from jinja2->torch<3.0.0,>=2.0.1->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 6)) (2.1.2)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.9/dist-packages (from sympy->torch<3.0.0,>=2.0.1->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 6)) (1.2.1)
Requirement already satisfied: h11<0.13,>=0.11 in /usr/local/lib/python3.9/dist-packages (from httpcore<0.17.0,>=0.15.0->httpx<1,>=0.23.0->openai>=0.27.8->-r /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/requirements.txt (line 1)) (0.12.0)
Building wheels for collected packages: moviepy, typing
  Building wheel for moviepy (setup.py) ... done
  Created wheel for moviepy: filename=moviepy-1.0.3-py3-none-any.whl size=110728 sha256=3d9fcff966031556118986e756789f40bc801b1764eb988f159a3ff46593f6a0
  Stored in directory: /root/.cache/pip/wheels/f0/23/29/c6379bde05643dcb1cd56f5ad432f26acb3ca7db075dc0c35f
  Building wheel for typing (setup.py) ... done
  Created wheel for typing: filename=typing-3.7.4.3-py3-none-any.whl size=26305 sha256=ca4bef5fd4b5e3bdd7c8d0394cc57808d70ae8c98d12014b6047c6a8690fc0e2
  Stored in directory: /root/.cache/pip/wheels/bf/97/61/e3c9316da01340cf1585f1f5a1c52d873f5023fb9f635385f2
Successfully built moviepy typing
Installing collected packages: py-cpuinfo, typing, scikit-build, safetensors, Pillow, opencv-python, einops, diskcache, huggingface-hub, gitpython, torch, moviepy, transformers, torchvision, openai, accelerate
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface-hub 0.11.1
    Uninstalling huggingface-hub-0.11.1:
      Successfully uninstalled huggingface-hub-0.11.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
img2texture 1.0.6 requires pillow<10,>=9.2, but you have pillow 10.2.0 which is incompatible.
clean-fid 0.1.31 requires requests==2.25.1, but you have requests 2.28.2 which is incompatible.
blendmodes 2022 requires Pillow<10,>=9.0.0, but you have pillow 10.2.0 which is incompatible.
Successfully installed Pillow-10.2.0 accelerate-0.26.1 diskcache-5.6.3 einops-0.7.0 gitpython-3.1.41 huggingface-hub-0.20.1 moviepy-1.0.3 openai-1.11.1 opencv-python-4.9.0.80 py-cpuinfo-9.0.0 safetensors-0.4.2 scikit-build-0.17.6 torch-2.2.0 torchvision-0.17.0 transformers-4.37.2 typing-3.7.4.3
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

I don't understeand it's saying found huggingface-hub==0.10.0 but i have installed huggingface-hub-0.20.1
