### ISSUE TITLE
Python 3.9 incompatible

### ISSUE THREAD

**Issue by davedaverave** [gokayfem/ComfyUI_VLM_nodes#7]
this the complete error Traceback (most recent call last):
  File "/notebooks/ComfyUI/nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/__init__.py", line 45, in <module>
    imported_module = importlib.import_module(f".nodes.{module_name}", __name__)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/nodes/joytag.py", line 1, in <module>
    from .joytagger import Models
  File "/notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/nodes/joytagger/Models.py", line 16, in <module>
    class VisionModel(nn.Module):
  File "/notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/nodes/joytagger/Models.py", line 27, in VisionModel
    def load_model(path: Path | str, device: str | None = None) -> 'VisionModel':
TypeError: unsupported operand type(s) for |: 'type' and 'type'

Cannot import /notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes module for custom nodes: unsupported operand type(s) for |: 'type' and 'type'

I maybe Guess that the union operator | with types type and type, is not supported in py 3.9 ...

**Comment by gokayfem** [comment]
yes it was added in Python-Version: 3.10

**Comment by davedaverave** [comment]
I can't update python as i'm running on paperspace, is there a way to fix that? or an alternative for us? thank you very much

**Comment by gokayfem** [comment]
you can delete the joytag from nodes by deleting from it __init.py__.py file inside VLM nodes there is a node_list, delete it from there
```
# BEFORE:
node_list = [
    "moondream_script",
    "prompter",
    "joytag",
    "simpletext",
    "llavaloader",
    "suggest",
]

# AFTER:
node_list = [
    "moondream_script",
    "prompter",
    "simpletext",
    "llavaloader",
    "suggest",
]
```

**Comment by davedaverave** [comment]
So it's actually working thanks, but... joytag was one of the two nodes i wanted from this plugin 🥲
Is there any other way around?

**Comment by gokayfem** [comment]
well i need to convert all of the not compatible operators in the ```nodes/joytag/Models.py``` to old ones, like ```|``` to ```or``` and try if it works. i dont know how many other operators that dont work.

**Comment by gokayfem** [comment]
okay i fixed ```|```

**Comment by davedaverave** [comment]
Wow, thanks!! I'm super gratefull 🙏
I'll try and get back to you as soon as possible 🫶

**Comment by davedaverave** [comment]
Joytag is fully functional!!!! THANKS
i would like to try [InternLM-XComposer2-VL](https://github.com/InternLM/InternLM-XComposer) is that possible or i need to use  LLaVa models?

**Comment by gokayfem** [comment]
not avaliable in my nodes, but there is some other nodes using it i dont know the name but i saw one of the workflow using it

**Comment by gokayfem** [comment]
> Joytag is fully functional!!!! THANKS
> i would like to try [InternLM-XComposer2-VL](https://github.com/InternLM/InternLM-XComposer) is that possible or i need to use  LLaVa models?

interlm added to the repo
