### ISSUE TITLE
RuntimeError: Failed to load shared library 'D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\llama_cpp\llama.dll

### ISSUE THREAD

**Issue by w84itngetit** [gokayfem/ComfyUI_VLM_nodes#82]
Successfully installed tokenizers-0.19.1 transformers-4.40.1
llama-cpp installed
All packages from requirements.txt are installed and up to date.
AutoGPTQ installed
Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\llama_cpp\llama_cpp.py", line 74, in _load_shared_library
    return ctypes.CDLL(str(_lib_path), **cdll_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "ctypes\__init__.py", line 376, in __init__
OSError: [WinError 1114] Произошел сбой в программе инициализации библиотеки динамической компоновки (DLL)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_VLM_nodes\__init__.py", line 70, in <module>
    imported_module = importlib.import_module(f".nodes.{module_name}", __name__)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_VLM_nodes\nodes\llavaloader.py", line 4, in <module>    from llama_cpp import Llama
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\llama_cpp\__init__.py", line 1, in <module>
    from .llama_cpp import *
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\llama_cpp\llama_cpp.py", line 87, in <module>
    _lib = _load_shared_library(_lib_base_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\llama_cpp\llama_cpp.py", line 76, in _load_shared_library
    raise RuntimeError(f"Failed to load shared library '{_lib_path}': {e}")
RuntimeError: Failed to load shared library 'D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\llama_cpp\llama.dll': [WinError 1114] Произошел сбой в программе инициализации библиотеки динамической компоновки (DLL)

Cannot import D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_VLM_nodes module for custom nodes: Failed to load shared library 'D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\llama_cpp\llama.dll': [WinError 1114] Произошел сбой в программе инициализации библиотеки динамической компоновки (DLL)

D:\AI\ComfyUI_windows_portable>pause

Hello) How can i fix that?

**Comment by Xenodimensional** [comment]
Looks like I have the same issue and I just wasted a night trying to get this to work. On the upside, deleting it didn't seem to tank my Comfy install.

Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\llama_cpp\llama_cpp.py", line 74, in _load_shared_library
    return ctypes.CDLL(str(_lib_path), **cdll_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "ctypes\__init__.py", line 376, in __init__
OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_VLM_nodes\__init__.py", line 70, in <module>
    imported_module = importlib.import_module(f".nodes.{module_name}", __name__)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_VLM_nodes\nodes\llavaloader.py", line 4, in <module>
    from llama_cpp import Llama
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\llama_cpp\__init__.py", line 1, in <module>
    from .llama_cpp import *
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\llama_cpp\llama_cpp.py", line 87, in <module>
    _lib = _load_shared_library(_lib_base_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\llama_cpp\llama_cpp.py", line 76, in _load_shared_library
    raise RuntimeError(f"Failed to load shared library '{_lib_path}': {e}")
RuntimeError: Failed to load shared library 'C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\llama_cpp\llama.dll': [WinError 1114] A dynamic link library (DLL) initialization routine failed

Cannot import C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_VLM_nodes module for custom nodes: Failed to load shared library 'C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\llama_cpp\llama.dll': [WinError 1114] A dynamic link library (DLL) initialization routine failed

**Comment by RandomMaxx** [comment]
I have exactly the same issue since updating my Comfyui and updating PyTorch, cannot say when exactly it started. Still think it might be related to my update. Am on 
### ComfyUI Revision: 2276 [1e2839f4] | Released on '2024-06-20'
** Python version: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
** Python executable: D:\Program Files\ComfyUI_windows_portable\python_embeded\python.exe
