### ISSUE TITLE
Moondream issue

### ISSUE THREAD

**Issue by gobshyte** [gokayfem/ComfyUI_VLM_nodes#94]
Hi
I am still getting this error despite trying all the fixes noted for previous issues on the subject? Is it broken again?

```
Traceback (most recent call last):
  File "C:\SDAI\ComfyUI\ComfyUI\nodes.py", line 1876, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\SDAI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_VLM_nodes\__init__.py", line 70, in <module>
    imported_module = importlib.import_module(f".nodes.{module_name}", __name__)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\SDAI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_VLM_nodes\nodes\moondream_script.py", line 1, in <module>
    from .moondream import VisionEncoder, TextModel
  File "C:\SDAI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_VLM_nodes\nodes\moondream\__init__.py", line 1, in <module>
    from .vision_encoder import VisionEncoder
  File "C:\SDAI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_VLM_nodes\nodes\moondream\vision_encoder.py", line 4, in <module>
    from torchvision.transforms.v2 import (
ImportError: cannot import name 'ToImage' from 'torchvision.transforms.v2' (C:\SDAI\ComfyUI\python_embeded\lib\site-packages\torchvision\transforms\v2\__init__.py)

Cannot import C:\SDAI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_VLM_nodes module for custom nodes: cannot import name 'ToImage' from 'torchvision.transforms.v2' (C:\SDAI\ComfyUI\python_embeded\lib\site-packages\torchvision\transforms\v2\__init__.py)
```

**Comment by gokayfem** [comment]
is this moondream2 or moondream1?

**Comment by gobshyte** [comment]
No idea sorry, this is fresh install of the VLM custom nodes.
I am not even using the moondream nodes/models, I worked around this by commenting them out in the nodelist in __init__.py, like this:
```

init()

node_list = [
#    "moondream_script",
    "simpletext",
    "llavaloader",
    "suggest",
    "joytag",
    "internlm",
    "uform",
    "kosmos2",
    "audioldm2",
    "playmusic",
    "mcllava",
#    "moondream2",
]
```

**Comment by gokayfem** [comment]
its probably related to transformers version of your comfyui python

**Comment by gobshyte** [comment]
I already tried with transformers>=4.38.2 but made no difference...

**Comment by gokayfem** [comment]
i will remove moondream1 node since probably everybody use moondream2 because they are almost same size.

**Comment by gobshyte** [comment]
Cool, I will try again later then, thanks

**Comment by gokayfem** [comment]
Resolved. The Moondream 1 node was removed as you and I discussed, and Moondream 2 was rewritten. Moondream 3 / 3.1 now run in an isolated Python environment specifically so their pinned `Pillow` and kernel requirements cannot conflict with ComfyUI's.

Commenting out entries in `node_list` is also no longer necessary — a module that fails to import is isolated automatically and only its own nodes go missing.
